import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import dynamic from "next/dynamic";
import { ExamplesNav } from "@/components/examples-nav";

const RootContainer = dynamic(
  () => import("@/components/container/root-container")
);
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <RootContainer>
            <section className="px-[40px] relative pt-[40px]">
              <ExamplesNav />
              <div className="overflow-hidden rounded-[0.5rem] border bg-background shadow">
                {children}
              </div>
            </section>
          </RootContainer>
        </ThemeProvider>
      </body>
    </html>
  );
}
